### ISSUE TITLE
Not receiving submission confirmations

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#194] opened 2016-02-01 22:53 UTC
There are two artists, Lindsey Walker and Barry Campbell, whose full music submissions are appearing at the URLs you sent me on Jan 14 (here they are without the auth token: https://ccrapi3.murfie.com/review-and-publish/artists/fall-2015/?auth= and https://ccrapi3.murfie.com/review-and-publish/albums/fall-2015/?auth=), but I have not received a confirmation email indicating that they have signed their licenses. @mbrakken do you know why that might be? I am worried I am late paying them their honorariums.

**Comment by acecarruthers** [comment] 2016-02-03 23:16
I also haven't received a confirmation of Kathleen Yearwood's submission #196, or Josh's submission, which he says is complete, #188

**Comment by acecarruthers** [comment] 2016-02-04 20:17
I have not received a confirmation of Marlon Wilson's submission for the band Politic Live, but his album appears online.

**Comment by acecarruthers** [comment] 2016-02-04 23:36
I have also not received a confirmation of Kaz Mega's album or the album RAANI submitted by Danny Fournier. 
@mbrakken can you confirm that the submissions of these musicians are complete so I can make sure they are paid on time? I typically send the payment information to our purchasing department on Fridays.

**Comment by acecarruthers** [comment] 2016-02-09 00:17
I have pushed my questions about Kathleen Yearwood, Marlon Wilson, Josh Sahunta and Raani over to #198. I did not received confirmations from Lindsey Walker, Barry Campbell and Kaz Mega, but those albums are also missing tracks, which makes them a bit more complicated.

**Comment by mbrakken** [comment] 2016-02-09 03:00
Notes to self:

Looking at server config, emails are being sent via smtp-relay.gmail.com with download.processing@murfie.com as the authing user. I have vague memory of password changes for that account back in December or something, and I don't know that the password in the config for the musicat api was ever updated (nor did I realize emails were being sent via that account).

If smtp auth is the issue, I don't know why it would have suddenly stopped working, but I can dig out the current password from other system configs in the morning and verify.

Ideally emails would be sent via a host / account inside either musicat or epl namespace.

**Comment by acecarruthers** [comment] 2016-02-09 16:03
I have still be receiving most confirmation emails, just not all of them.

**Comment by acecarruthers** [comment] 2016-03-07 23:00
Barry has now successfully uploaded his tracks and everything is done. He mentioned that he received an "invalid character" error message when he tried to submit the license using Google Chrome and had to try again in Firefox.

**Comment by acecarruthers** [comment] 2016-03-08 23:57
Lindsey has also successfully updated her album. She mentioned that she had trouble uploading an mp3 and could only successfully upload a WAV file.

**Comment by kellyhiser** [comment] 2016-03-15 14:27
Summary of this issue: Alex is not receiving confirmation emails for all signed licenses. Artists for whom data for signed license exists but for whom Alex did not receive confirmation are:

1. Lindsey Walker "signed_date": "2016-01-26T05:55:23.232Z",
2. Barry Campbell "signed_date": "2016-01-30T01:46:59.234Z",
3. Kathleen Yearwood "signed_date": "2016-02-02T23:48:32.890Z",
4. Josh Sahunta "signed_date": "2016-01-16T23:27:14.867Z",
5. Marion Wilson (Politic Live) "signed_date": "2016-02-04T19:22:19.449Z",
6. Kaz Mega "signed_date": "2016-02-04T20:47:30.887Z",
7. Danny Fournier (Raani) "signed_date": "2016-02-04T17:39:23.882Z",

**Comment by prestonaustin** [comment] 2016-03-15 14:48
@kellyhiser So I'm clear, my understanding is that this is problematic
because EPL doesn't get the affirmative notice, and doesn't have a
consistent email inbox "log" to refer to historically.

Are there other administrative or artist support problems caused by not
receiving these?

I ask because I may explore alternative ways to meet needs these emails
meet, if resolving the intermittency proves difficult or those needs are
better met within MUSICat admin or reports.

**Comment by kellyhiser** [comment] 2016-03-15 14:53
@prestonaustin Yes, that's correct. Alex needs to know a signing date so that she has a record, and needs a way to be updated irt as licenses are signed so that she can promptly send payment to artists.

**Comment by acecarruthers** [comment] 2016-03-15 15:23
@kellyhiser I have received confirmation emails from:
- Lindsey Walker
- Barry Campbell
- Kathleen Yearwood
- Josh Sahunta

I have received complete submissions from Marlon Wilson and Danny Fournier but no email confirmations. Kaz Mega's album remains incomplete and he is waiting for a prompt to try re-uploading. 

@prestonaustin In addition to what Kelly mentioned, an important thing about the email confirmations is that it is where I can see the artists' mailing addresses. I need their addresses to send them their cheques.

**Comment by kellyhiser** [comment] 2016-03-15 15:32
Thanks, @acecarruthers. Do you currently need email addresses for the 3 folks you didn't receive confirmation for (Wilson Mega, and Fournier)? I can email those to you if that's the case. 

I'm going to detach this from the Call for Submissions milestone and move to a Longterm Bug milestone. Requirements for license signing notification are:
1. notification irt 
2. record of date signed
3. record of artist email address

**Comment by acecarruthers** [comment] 2016-03-15 15:35
Thanks @kellyhiser I don't need email addresses for these artists because I get those when I am CC'd on their initial invitations. I would revise number 3 in your list above to say "record of artist home mailing address (street address)"

**Comment by kellyhiser** [comment] 2016-03-15 16:55
@acecarruthers do you need mailing addresses then? I can pull from data endpoints and email if you do.

**Comment by acecarruthers** [comment] 2016-03-15 16:58
Thanks @kellyhiser but there is no need. I have access to the data endpoints and I have already paid Marlon and Danny. I have recorded Kaz's address for future use just in case.

**Comment by kellyhiser** [comment] 2016-05-24 14:41
I think we'll be able to confirm this after going through this process with Seattle PlayBack, though I'm not sure that CCR email stuff is in the same state as SPB email, so we'll need to make sure of that. Complete Submissions is scheduled roughly for June 16 - 30, so I'd expect us to know if problems exist during the week of the 20th.

**Comment by prestonaustin** [comment] 2016-06-21 19:42
- [ ] retest when rest of round is ready, specifically confirm that notice of signed license goes out

**Comment by acecarruthers** [comment] 2016-07-08 17:08
please log the send attempts somewhere that I can view

**Comment by prestonaustin** [comment] 2016-07-11 15:16
- [ ] Add logging of sends so that deliverability to Alex isn't a confound

**Comment by kellyhiser** [comment] 2016-10-12 12:54
closing as this should just work after CCR is moved to new server, stemified, etc.

**Closed by kellyhiser** 2016-10-12 12:54 UTC
Labels: blocked, bug, EPL blocker
