### ISSUE TITLE
Library Customers Can't Log In to CCR

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#231] opened 2016-05-02 17:49 UTC
This was initially reported by a customer whose card number is 21221024386838. I can send you the PIN privately if you need. He emailed me about it Friday April 29 at 3:49PM MT. 

I seem to be able to log in fine, so can a colleague, but another colleague is having trouble. Our ILS administrator tried a staff card, a test card, and a customer card and could not log in with any of them. 

Let me know what additional information I can put together to support the resolution of this issue.

**Comment by prestonaustin** [comment] 2016-05-02 18:03
This sounds like cached queries are working and new ones aren't, at an
initial guess. That implies our API is nominally "up" and responding but
can't speak to the SIP2 gateway. We'll start there and update this ticket
with what we discover. If you know of changes to network ACLs or SIP2
service (hosted at the university if I recall) post them here, but don't
put a lot into searching for that until I come back with more info.

**Comment by mbrakken** [comment] 2016-05-02 18:19
Did EPL update whitelisting of servers? If so, did they de-list the prior
one?

Currently the app points to the old server (musicat-api-1, aka
ccrapi3.murfie.com) for auth, because that *was* the authorized server. If
they've changed configs on their end, in theory it's as simple as updating
config in the the client app to point to api.capitalcityrecords.ca.

**Comment by prestonaustin** [comment] 2016-05-02 18:39
Marc: I have not yet requested an update to include the new server in EPL
ACLs.

**Comment by prestonaustin** [comment] 2016-05-02 19:12
@acecarruthers @mbrakken I've restarted the server in debug mode, and it thinks it is talking to the SIP2 service and appears to _actually be_ talking to the SIP2 service. I could use 3 library cards and pins to test with:
one that SHOULD work and IS NOT working
one that SHOULD work and IS working
one that SHOULD NOT work (and, presumably, isn't)

Log message of a test:
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 0       parameters.target_endpoint: cardvalid
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 0       parameters.selected_stage: Library Card Validation
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 1       Validating credentials for card bogus1
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 0       Connecting to SIP gateway eplapp.library.ualberta.ca
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 0       Connected to SIP gateway eplapp.library.ualberta.ca
Mon May 02 2016 19:02:42 GMT+0000 (UTC) 0       Logging on terminal user <omitted>
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 1       Message recived from SIP gateway
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 1       <ommited>
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 0       Terminal user rabble logged-in to SIP gateway eplapp.library.ualberta.ca
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 0       Requesting patron status for card bogus1
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 1       Message recived from SIP gateway
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 1       <stuff>user not found<stuff>
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 1       Patron status indicates card bogus1 is not valid
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 0       Disconnecting from SIP gateway eplapp.library.ualberta.ca
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 0       Connection to SIP gateway eplapp.library.ualberta.ca closed
Mon May 02 2016 19:02:43 GMT+0000 (UTC) 0       authorized: false

**Comment by acecarruthers** [comment] 2016-05-02 19:50
I emailed them to you @prestonaustin

**Comment by prestonaustin** [comment] 2016-05-02 19:59
Received.
OK, it appears the SIP2 conversation is not at fault, all of these cards work as they should in terms of authentication with the gateway. I'm now looking at some issue with the user records on the new API server as a likely culprit.

**Comment by acecarruthers** [comment] 2016-05-02 20:00
@anisbet is the ILS administrator here at EPL who might be able to answer questions about things on our end.

**Comment by prestonaustin** [comment] 2016-05-02 20:02
@anisbet @acecarruthers  I'm pretty sure it's all on our side (an issue on the new Rabble server) at this point. At first I thought the SIP2 gateway had to be involved, but now I just think it's something after we authorize the card with the gateway, because all of its responses are exactly as I would expect them to be for the test cards Alex provided.

**Comment by anisbet** [comment] 2016-05-02 20:56
I took a look at SIP2 responses with 3 cards, staff, customer, and a test card, and they SIP2 server is responding normally with customer status OK and valid. Which SIP2 port are you attaching to at EPL btw?

**Comment by prestonaustin** [comment] 2016-05-02 21:06
@anisbet - I've confirmed that it isn't SIP at all, that's all working beautifully and then we fail to create the new user for folks we haven't authorized before on our end, which I'm deploying a fix for shortly.
But, here's how and where we connect at the moment:
        SIP_HOST: "eplapp.library.ualberta.ca",
        SIP_PORT: "6133",
        SIP_TERMINAL_USER: "[omitted from source control]",
        SIP_TERMINAL_PASS: "[omitted from source control]",
        SIP_INSTITUTION: " "

**Comment by anisbet** [comment] 2016-05-02 21:08
Thanks! Let me know how you get on.

**Comment by prestonaustin** [comment] 2016-05-02 21:21
@acecarruthers I believe I have this fixed. Can you test things work as expected at https://wax.capitalcityrecords.ca/ and I'll move the fix to production. If all is going as expected, you should also find Hakiko, Max Uhlich in the collection of the "Test card that should work and is not working" that you provided me.
Reopen here if you find problems with any other cards at this time.

**Comment by acecarruthers** [comment] 2016-05-02 21:23
Everything is working as it should on the test site. Thanks @prestonaustin

**Comment by prestonaustin** [comment] 2016-05-02 21:34
@acecarruthers Cool. It's in the commits here, but the necessary change was minor, app/services/current-user.js was not namespacing itself to the appropriate X-Musicat-Collection so the API was refusing the user creation requests. This was a bug we introduced in making the API-Client conversation multi-namespace capable. Deploying and closing. @anisbet Thanks for checking SIP, we're all good on that front (and I hope on this one too :)

**Closed by prestonaustin** 2016-05-02 21:34 UTC
Labels: bug
