### ISSUE TITLE
New posters not showing on page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#124] opened 2015-08-19 18:18 UTC
I uploaded 15 JPG posters on either Monday or Tuesday (I forget) using the poster upload tool (http://submissions.capitalcityrecords.ca/submit/event-media) and immediately published them using the publishing tool (http://submissions.capitalcityrecords.ca/review-and-publish/posters). All 15 posters have "Voice Industrie" in their Collection name field. 

On the day that I published them I could see them on the poster page no problem from multiple devices. Today the images are breaking. See screenshot:  

![postererr](https://cloud.githubusercontent.com/assets/7355887/9364865/acd7e52a-466b-11e5-9c4e-25d559b8520d.png)

They are also broken on the poster publishing tool page when you select "show published." 

I have sent the Royal Alberta Museum a link to the poster upload tool because they have a collection of posters to share with us. Is this a problem with uploading? Should I tell the museum to wait until we have this sorted out? 

Thanks

**Comment by prestonaustin** [comment] 2015-08-19 18:28
Hmmm, this may be an impact of our storage crash we did not know about. I
thought CCR had no effects. @jjg were these possibly in between last backup
and crash?

If so, we probably need a recipe to repair this for @nagapampa, so the DB
matches the objects and has correct access keys. I assume we would want to
use same paths and set the keys on POST from what is in redis?

**Comment by jjg** [comment] 2015-08-19 18:35
The backup I restored was from 08/13, so if they were uploaded between then and yesterday they were likely lost due to the crash.

**Comment by acecarruthers** [comment] 2015-08-19 22:30
They definitely were uploaded between 08/13 and yesterday. 

It seems unlikely, but I want to confirm, do you anticipate that there will be a problem with posters that are uploaded today or tomorrow? 

If there won't be a problem I will re-upload the posters as well as some new posters. I don't have the ability right now to delete the records for posters that we lost, so I'll have to ask someone at Rabble to do that for me.

**Comment by prestonaustin** [comment] 2015-08-19 23:01
@acecarruthers I've confirmed with @jjg that we expect no issue with
re-uploads now, the server has a great deal more headroom and fixes to
cause of error are ongoing. We'll deal with the orphaned records from the
prior upload that was lost. Sorry about this and the audio problem - we
keep finding stuff related to that last minute switch if hosting to make
the DNS/SSL work - in this case we had issues we hadn't ironed out of this
app because our beta was not run on our load balancing environment. My
apologies for the hiccups :(

**Comment by acecarruthers** [comment] 2015-08-19 23:06
Thanks @prestonaustin, we appreciate your speedy resolution to the issues!

**Comment by acecarruthers** [comment] 2015-08-25 22:10
I think the remaining action on this issue is to remove the orphaned records so they no longer appear on the site

**Comment by acecarruthers** [comment] 2015-08-27 17:23
Can you also remove this poster https://capitalcityrecords.ca/posters/f97ab32174138d06e99422773d8592aee9216b22-2015-08-27t17-15-47-654z-11211602_10153248879812560_130433929_o-jpg 

it is actually just a logo thrown in with a big batch of posters.

**Comment by acecarruthers** [comment] 2015-09-23 15:30
Can removing the broken images be part of the next deploy? Do you need anything from me to make this happen?

**Comment by mbrakken** [comment] 2015-10-02 19:47
@acecarruthers I just deployed updates for unpublishing content. I only have UI affordances for it on posters right now, but that seems to be the main area it's needed.

In the tab for published posters at https://submissions.capitalcityrecords.ca/review-and-publish/posters you'll see separate buttons for Update and Unpublish. Currently the Unpublish removes the content from the public site and moves it into the unpublished queue. I successfully tested it on a couple items with broken images.

Note, because of the quantity of posters, the UI does hang for a few seconds while things are rerendering. The next wave of work should see general improvements on that kind of thing, though.

When I'm confident that everything is working fine for you, I can add a "Delete" button from the unpublished content queue. NB: that next button will effectively remove it from everywhere in the ccr-verse.

I think a two stage process of Unpublish --> Remove makes sense for now (or the near future), but please let me know if you think otherwise. We can also use this in the future to clean up all the test stuff still kicking about, but I'm going to focus on more pressing concerns for the immediate future.

Best

**Comment by mbrakken** [comment] 2015-10-05 18:58
I believe this is addressed with the addition of "unpublish" on posters. Closing. @acecarruthers please reopen if I am mistaken.

**Closed** 2015-10-05 18:59 UTC
Labels: bug, question

**Comment by acecarruthers** [comment] 2015-10-05 19:41
This worked perfectly! Thank you @mbrakken
