### ISSUE TITLE
Clicking site logo from posters page doesn't link you anywhere

### ISSUE THREAD

**Issue by JohnAtMurfie** [therabble/ccr-app#57] opened 2015-07-10 15:35 UTC
It should return you to the front page as expected when clicking the logo. When on the posters page or on an individual poster, clicking the log doesn't seem to do anything.

(John's Chrome on Chrome OS, https://wax.capitalcityrecords.ca/posters, 10 Jul, 10:35c)

**Comment by mbrakken** [comment] 2015-07-16 21:30
FYI, I couldn't reproduce. It worked as appropriate. Possibly, the handler was blocked/deferred due to image download/rending.

**Comment by prestonaustin** [comment] 2015-07-16 21:33
Please ask John to retest, and close the ticket. He can reopen if it fails.

**Comment by mbrakken** [comment] 2015-07-16 21:35
@JohnAtMurfie can you retest? :)

**Comment by JohnAtMurfie** [comment] 2015-07-16 21:45
@mbrakken I am able to duplicate the issue. When I go directly to the posters page, then click the logo, it works. If I start at the main page, then go to the posters page, clicking the logo doesn't work for me. I didn't realize this when I submitted the ticket.

@prestonaustin GitHub will not allow me to reopen this ticket. I can only comment.

**Comment by prestonaustin** [comment] 2015-07-16 21:49
Reopened, this should be enough for @nagapampa to work with when she gets to this one.

**Comment by nagapampa** [comment] 2015-07-17 01:49
Merged into master.  In next deploy.

**Closed by nagapampa** 2015-07-17 01:49 UTC
Labels: bug, non-blocking
