### ISSUE TITLE
album art not always loading

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#91] opened 2015-07-23 19:52 UTC
Album art in the playbar does not always load (as below) sometimes the same happens with album art on the album pages. In the example below, none of the album art initially showed. Then, once the first song was done and it moved to the left on the playbar, the album art appeared. 

I've noticed this a few times. It doesn't always happen, but it has happened enough that I thought I'd mention it just in case it isn't addressed by one of the planned updates. I will try to record other instances of this happening. 

(Alex, Firefox 39, https://wax.capitalcityrecords.ca/albums/the-duettes-your-little-voice 23 July, 1:40pm MT)

![album art](https://cloud.githubusercontent.com/assets/7355887/8860522/aeba8f26-3141-11e5-842f-fee4765d43b3.jpg)

**Comment by nagapampa** [comment] 2015-07-25 01:36
@prestonaustin I am unable to reproduce.

@acecarruthers Can you update this when it happens again and try to include a screenshot of the console to show any possible errors (press F12 in Chrome and go to console)

**Comment by prestonaustin** [comment] 2015-07-27 19:14
I sort of expect this to come back, but various continuing improvements to MMS may be concealing a race condition (basically, making a bug not show up) so I'm closing it until we have more information to work with.

**Closed by prestonaustin** 2015-07-27 19:14 UTC
Labels: bug, non-blocking
